# Generated by Django 4.2.4 on 2023-10-21 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.CharField(max_length=250, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Livre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=250)),
                ('auteur', models.CharField(max_length=250)),
                ('publication_date', models.DateField(null=True)),
                ('download_number', models.IntegerField(default=0)),
                ('description', models.TextField(null=True)),
                ('couverture', models.ImageField(upload_to='couverture')),
                ('pdf', models.FileField(upload_to='pdf')),
                ('url_pdf', models.URLField(default='none')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Livre.categorie')),
            ],
        ),
        migrations.CreateModel(
            name='compteur_de_telechargement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('livre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Livre.livre')),
            ],
        ),
    ]
