# Generated by Django 4.2.4 on 2023-10-28 10:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Livre', '0003_categorie_date_compteur_de_telechargement_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livre',
            name='date',
        ),
        migrations.AddField(
            model_name='livre',
            name='prix',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='categorie',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='compteur_de_telechargement',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='livre',
            name='publication_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
