# Generated by Django 4.2.4 on 2023-11-05 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Livre', '0005_commentaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentaire',
            name='is_valide',
            field=models.BooleanField(default=False),
        ),
    ]
