# Generated by Django 4.2.4 on 2023-11-22 23:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Livre', '0008_commande'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande_special',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('livre_titre', models.CharField(null=True)),
                ('livre_auteur', models.CharField(null=True)),
                ('livre_date_pub', models.DateTimeField(null=True)),
                ('date_commande', models.DateTimeField(auto_now_add=True)),
                ('couverture', models.ImageField(null=True, upload_to='couverture')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
