# Generated by Django 4.2.4 on 2023-11-23 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Livre', '0009_commande_special'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande_special',
            name='nom_prenom',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='commande_special',
            name='couverture',
            field=models.ImageField(null=True, upload_to='couverture_speciale'),
        ),
    ]
