# Generated by Django 4.2.4 on 2023-11-26 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Livre', '0010_commande_special_nom_prenom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande_special',
            name='livre_date_pub',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commande_special',
            name='nom_prenom',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
