# Generated by Django 4.2.4 on 2023-11-29 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Livre', '0011_alter_commande_special_livre_date_pub_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
