# Generated by Django 4.2.4 on 2023-11-29 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Livre', '0013_alter_commande_special_couverture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande_special',
            name='livre_date_pub',
            field=models.DateTimeField(blank=True, default='1999-12-31 00:00', null=True),
        ),
    ]
