# Generated by Django 4.2.4 on 2023-11-29 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Livre', '0014_alter_commande_special_livre_date_pub'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande_special',
            name='livre_date_pub',
        ),
    ]
