# Generated by Django 4.2.4 on 2023-11-30 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Livre', '0015_remove_commande_special_livre_date_pub'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livre',
            name='url_pdf',
        ),
        migrations.AlterField(
            model_name='livre',
            name='publication_date',
            field=models.DateField(default='none', null=True),
        ),
    ]
