# Generated by Django 4.2.4 on 2023-11-30 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Livre', '0016_remove_livre_url_pdf_alter_livre_publication_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livre',
            name='publication_date',
            field=models.DateField(default=1957, null=True),
        ),
    ]
