# Generated by Django 4.2.4 on 2023-11-30 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Livre', '0018_alter_livre_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livre',
            name='publication_date',
            field=models.DateField(default='2000-12-31', null=True),
        ),
    ]
