# Generated by Django 4.2.4 on 2023-11-30 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Livre', '0019_alter_livre_publication_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande_special',
            name='livre_date_pub',
            field=models.DateField(blank=True, default='1999-12-31', null=True),
        ),
    ]
