# Generated by Django 4.2.4 on 2023-11-30 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Livre', '0020_commande_special_livre_date_pub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande_special',
            name='livre_date_pub',
            field=models.DateField(default='2000-12-31', null=True),
        ),
    ]
